# Jekyll configuration

name: prince of abyss
description: just a blog where an idiot shares his thoughts and crappy writing

# Url is currently only used only for the RSS feed in feed.xml
url: http://iron131211.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: iron
copyright: 

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  twitter: 'iron131211'
  
disqus: iron131211
  
permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
